### ISSUE TITLE
Add support for TOTP and HOTP generation

### ISSUE THREAD

**Issue by mossholderm** [pfn/keepshare#10]
This allows for logging into sites with two factor authentication. Google authenticator oi is a good example of this. Plugins exist for support in Keepass.

**Comment by pfn** [comment]
{hmacotp} is already supported. it works identically as-in keepass (set the various HmacOtp-* keys as necessary, and put {hmacotp} into the password field).

totp will be investigated separately.

**Comment by pfn** [comment]
Set one of the following:
* `HmacOtp-Secret`: plain string shared secret
* `HmacOtp-Secret-Hex`: hex-encoded shared secret
* `HmacOtp-Secret-Base32`: base32-encoded shared secret
* `HmacOtp-Secret-Base64`: base64-encoded shared secret

Additionally, set this to the correct value for your current otp
* `HmacOtp-Counter`: generation counter for hmacotp password

**Comment by pfn** [comment]
Usage:

Fill in one of the `HmacOtp-Secret` fields as documented above (re-uses existing HmacOtp support)

Optionally, configure any of the following fields:

* `TimeOtp-T0`: set to the initialization time, if any, defaults to `0`; do not change this
* `TimeOtp-Step`: set to the Time Step of the TOTP, defaults to `30`, do not change this
* `TimeOtp-Size`: size of the resulting OTP, defaults to `6`, change this to match your provider's requirements

The OTP is generated by the SprEngine automatically, all you need to do is fill in the field of your choice with `{TOTP}`

**Comment by pfn** [comment]
Further improved by 468f9508c952031232558878b921cdad47d51bf0

Automatic display in an OTP view with a time remaining bar (TOTP only at the moment)
