### ISSUE TITLE
After entering database password in setup, default keyboard remembers my password

### ISSUE THREAD

**Issue by ezheidtmann** [pfn/keepshare#11]
After completing setup in KeepShare Lite, I've discovered that my KeePass database password is saved as a new word (i.e. available for auto-correct). Is this a bug in KeepShare?

I'm using a Samsung Galaxy S5 on Verizon, using the default "samsung keyboard". Happy to provide more information if it would be helpful.

-Evan

**Comment by pfn** [comment]
Interesting bug, I haven't encountered this using swiftkey. Does the
suggestions bar appear while entering your password?

**Comment by ezheidtmann** [comment]
Good question! Just checked and yes, it does.

**Comment by pfn** [comment]
Different keyboards have different mechanisms for hiding the suggestion bar
on password fields, I'll see if there's something that can be done for the
samsung keyboard.

**Comment by pfn** [comment]
can you verify this on 4.2.0? it may have been fixed by other changes that occurred around the password input for the database

**Comment by ezheidtmann** [comment]
Hey there. I just checked the DB setup screen on 4.2.1 and it looks like the original problem is fixed. I can enter my password in the password field and it's not saved to my keyboard's dictionary. :+1: 

However, when I return to the DB setup screen I see my password in plaintext in the key file field. I am using a key file, so I can't leave this screen until I find my key file and re-enter my password.

![screenshot_2015-12-24-09-24-41](https://cloud.githubusercontent.com/assets/1178915/11996837/a494ff1a-aa20-11e5-827b-c5d88e47810e.png)

**Comment by pfn** [comment]
Fixed in 4.2.2

**Comment by ezheidtmann** [comment]
Verified. Excellent! :+1:
