### ISSUE TITLE
Android 6 w/ SwiftKey - keyboard immediately dissappears

### ISSUE THREAD

**Issue by Zxurian** [pfn/keepshare#12]
Just did a factory install of Marshmallow, Installed KeepShare Lite (already had swiftkey installed). App runs, I can hit browse and select my database file, but upon tapping in the Password field, keyboard shows briefly, then is immediately gone.
Same thing happens if I tap in the Key File field.

**Comment by k8seren** [comment]
I'm having the same issue. Any fix for this? It says to enable custom keyboard, but there is no KeePass keyboard to select. I'll pay for the full version if I can get Lite to work.

**Comment by pfn** [comment]
Should be fixed in 4.2.0, by e3ca7b819bf186f535c
