### ISSUE TITLE
Why is it mandatory to connect to Google Drive?

### ISSUE THREAD

**Issue by zmLGBBM** [pfn/keepshare#13]
I'm using OneDrive to store my KeePass database, since in china, it's impossible to use any `google` stuff. However, it seems that `KeepShare` requires to connect to Google Drive to store some `key file`. So I'm wondering if this could be made optional?

**Comment by pfn** [comment]
The connection to google drive is used to store secret key material that prevents hacking of your pin code when offline. It is this secret key that keeps your data secure. 

I would not publish this solution using pin code if the  private storage were not available. It cannot be made optional without destroying system security. 

Unfortunately, I don't believe any of the other storage providers, eg OneDrive, offer a similar capability to store private app data.

**Comment by zmLGBBM** [comment]
@pfn Well, I guess this is it.. The most secure part of `KeePass` to me is it does not require any internet connection.

Anyway, thanks for the amazing app and happy holiday! ;)

**Comment by pfn** [comment]
KeePass doesn't let you unlock your database with a 4 digit pin while not being hackable in 2 seconds. 

In the future, I may be able to drop the google drive requirement for android 6 and above if one has a fingerprint scanner. 

There is no other secure way.

**Comment by zmLGBBM** [comment]
@pfn That would be nice. 

If a 4-digit pin could be hacked in 2 seconds, then why not use master password instead.

**Comment by pfn** [comment]
Because a master password is too hard to type and breaks usability.

With google drive integration implemented in keepshare, the PIN cannot be
hacked.
