### ISSUE TITLE
Crashes, bugs when reconnecting database

### ISSUE THREAD

**Issue by dazweeja** [pfn/keepshare#14]
I had a KeePass 2.x database working fine in Keepshare. I then changed the security on this database externally, ie. changed master password and added key in KeePass on my PC. This required me to reconnect the database in Keepshare. This led to a number of issues:

1. If I didn't try to set PIN immediately after connecting the database, Keepshare would immediately forget the database connection settings, ie. location, password, key.

2. If I did try to set PIN immediately after connecting the database, I would get to the confirm PIN screen and even after entering the PIN, the OK button would do nothing, ie. I could see it changing state but no action would be taken and no error message.

3. Occasionally Keepshare would crash during steps 1 and 2.

I believe what eventually resolved the issue was manually deleting the app data for Keepshare in Google Drive. I disconnected app there too just in case.

I'm wondering if Keepshare might perform more reliably if existing app data in Google Drive was automatically deleted by the app when connecting a database that has previously been connected.

**Comment by pfn** [comment]
Please verify against 5.1.1 when it becomes available.

**Comment by pfn** [comment]
The crashes were unrelated to 1 and 2, can you write new repro steps now that the crashes have been cleared out of the way (if you encounter this again). Thanks

**Comment by pfn** [comment]
closing due to lack of feedback
