### ISSUE TITLE
Truncate URL on password select overlay

### ISSUE THREAD

**Issue by dazweeja** [pfn/keepshare#15]
Some websites make extensive use of query strings which leads to extremely long URLs. This breaks the functionality of the password select overlay in KeepShare, ie. action elements such as the search icon and the buttons are not visible on the overlay so no action can be taken. May I suggest truncating the URL on this overlay to 3 or 4 lines or whatever you feel is reasonable? I've attached an example where this is an issue:

![screenshot_20151231-145453](https://cloud.githubusercontent.com/assets/154635/12072782/851390e8-b146-11e5-9f85-030f6daec98f.png)

**Comment by pfn** [comment]
Oops, this was done for the keyboard prompt, but not for form fill, thanks for the reminder. Will be released as 5.1.2 when I get the chance
