### ISSUE TITLE
Adding colored display of different characters in passwords

### ISSUE THREAD

**Issue by matze787** [pfn/keepshare#16]
it'll be great if the password would be shown like the way the android version of Lastpass does - colored depending on its being a number, a normal character or a special character (like @). Please take a look here:

http://cdn01.androidauthority.net/wp-content/uploads/2015/12/lastpass-Password_Generator.jpg

Sometimes I have to use passwords on the PC at work where I have no Keepass. Unfortunately there are some characters that seems similar like "I" and "l" for example...

Thank you very much!

**Comment by pfn** [comment]
![Passwords Colored](http://i.imgur.com/0LJTJLI.png)
