### ISSUE TITLE
Adding password generator

### ISSUE THREAD

**Issue by matze787** [pfn/keepshare#17]
As much as I love Keepshare - but a integrated password generator is extremely missing. Please add a password generator with the ability to determine password length, which characters shall be included etc.

I used a lot of password managers but they all included this functionality by default.

Thank you very much!

**Comment by pfn** [comment]
https://www.youtube.com/watch?v=71Blp0mW7oc sample of how it looks like (although now it has a refresh and copy-to-clipboard buttons as well)
