### ISSUE TITLE
App Crash on fingerprint authentication 

### ISSUE THREAD

**Issue by Schokobecher** [pfn/keepshare#18]
Hey, 
I'm getting a force-close on fingerprint authentication. 
Using ZUK Z1 with unofficial CM13 nightlies. 

Logcat attached. 
[2016-03-08-09-54-08.txt](https://github.com/pfn/keepshare/files/162809/2016-03-08-09-54-08.txt)

**Comment by pfn** [comment]
Do you use your fingerprint to unlock your phone?

If not, it may result in this error (this is a configuration I have never tested).

**Comment by Schokobecher** [comment]
Yes, 
other Apps like Telegram and Authenticator+ work fine. Funny enough, keepass2android has a similiar issue

**Comment by pfn** [comment]
In all likelihood, telegram and authenticator probably use it to identify
your fingerprint and do not use it to secure your actual private key data.
If that is the case, they are not secure.
