### ISSUE TITLE
[Feature Request] add ability to copy password to clipboard

### ISSUE THREAD

**Issue by thy1985** [pfn/keepshare#23]
hi there

looks like there is no way to get a password out of an entry besides unhiding it, select all, copy. A button to copy the password to the clipboard (as it is found in Keepass(x), Macpass et al) would be really great.

Optionally clipboard would become cleared after X seconds. No idea if this is feasible from the technical point of view for Android and/or if it is left out due to security considerations? (Maybe an "I accpet the risk" tick in the settings is the way out...)

Cheers,

**Comment by pfn** [comment]
I generally prefer not to enable copying password to clipboard due to the
security implications. There is a button for loading directly into
keyboard, which alleviates that pain.

**Comment by thy1985** [comment]
right, that button did not work for me. however i figured out that this is related to an app I use for automated keyboard swapping (based on active app...). So adding an exclusion for keepshare there did the trick
