### ISSUE TITLE
Does KeepShare support plugins in general and specifically KeePassHttp?

### ISSUE THREAD

**Issue by fab-io** [pfn/keepshare#26]
Hi, I'm searching for managing secrets for my home servers directly from my phone, so a combination of KeePass for Android with a plugin like KeePassHttp is actually what I'm looking for.

Does KeepShare support plugins in general and specifically KeePassHttp?

thanks,
 Fabio

**Comment by pfn** [comment]
Plugins are not supported and for that matter, keepasshttp isn't very
viable on android (keepshare does everything one would want within the
device itself) -- as for use as a server, I really wouldn't want to expose
that interface
