### ISSUE TITLE
Stuck while retrieving key from Google Drive

### ISSUE THREAD

**Issue by teresaejunior** [pfn/keepshare#31]
I have struggled with this problem for the past few weeks: when I type the PIN to unlock KeepShare, it constantly gets stuck in a loop while retrieving the key from Google Drive. Generally, I have to kill KeepShare multiple times and retype the PIN, until it can retrieve the key from Google Drive successfully!

I have checked my network connection multiple times when this happened, and it was always working well! Connecting to Google works well, and also I have not found any problems using the Google Drive application!

Thank you for your support!

![screenshot_2016-06-21-11-56-25_com hanhuy android keepshare lite](https://cloud.githubusercontent.com/assets/3650039/16270984/95425c10-386e-11e6-9a19-447e5af8420b.png)

**Comment by pfn** [comment]
If you're technical enough and able to retrieve logcat from the device
while this occurs, it would be appreciated to determine what is happening.

I am unable to reproduce this across an array of devices  :-(

**Comment by teresaejunior** [comment]
OK, I'm going to try! Thank you for your attention!

**Comment by teresaejunior** [comment]
Hello! I have done the following steps:

1) Run `adb logcat -c; adb logcat >logcat.txt`;
2) Opened KeepShare and typed the PIN;
3) Let it try fetching the key for some time;
4) Gave up and touched the Home button;
5) Came back to KeepShare, it was now asking for the PIN again.

This is the output: [logcat.txt](https://github.com/pfn/keepshare/files/333693/logcat.txt).

**Comment by pfn** [comment]
Is this your own build of keepshare?

**Comment by teresaejunior** [comment]
No, it's from Google Play!

**Comment by pfn** [comment]
That's so weird, the logs indicate that the apk has an invalid signature,
shouldn't be possible if it's downloaded from Google play. I'll have to
investigate further. Thanks for the log

**Comment by teresaejunior** [comment]
I stopped rolling my own build of KeepShare years ago, and I have never installed that build on this device! The only "unusual" thing on my device could be that the pre-installed system is MIUI instead of Android, although most vendors modify Android a lot too!

I thought I had mentioned this in the first message, but this problem does not always happen, although it happens more frequently than not, that's why I considered it bad enough to be reported!

Thank you again for your attention!

**Comment by pfn** [comment]
http://stackoverflow.com/questions/37333220/googlesignatureverifier-signature-not-valid-message-google-play-services-9-0-0

Sounds like it's a google play services bug on-device, the problem should go away when your device gets a newer version pushed to it.

**Comment by teresaejunior** [comment]
OK, thank you! I hope it will be fixed soon, since it was acknowledged by a Google engineer on that link!

**Comment by teresaejunior** [comment]
I have downgraded Google Play Services to version 8.1.15, and this problem actually still happens, but the logcat is now different: [logcat.txt](https://github.com/pfn/keepshare/files/340303/logcat.txt)

Thank you again for your attention!

**Comment by pfn** [comment]
So weird, the log shows this line:

W/ActivityResultManager( 3224): Request code 6 not found: null

(which isn't an error in itself)

that means the response from PIN entry was completed, and the database
should be appearing -- instead you say it's stuck on the dialog saying it's
fetching key from google drive?

**Comment by teresaejunior** [comment]
Yes, exactly!

**Comment by pfn** [comment]
In the mean time, perhaps try clearing data and setting the database/pin up
again?

**Comment by teresaejunior** [comment]
I have done as requested, but I have not seen any change! The only thing I can think of is the DNS for the 4G connection, but I have not found a way to change it without rooting the device, and you said the logcat shows a successful operation, which is odd!

**Comment by pfn** [comment]
I'll have to make a special build for you that tracks pin authentication
closely to see where it is getting stuck. I've already added cloud key
retrieval failure logging, and have not seen any of those failures occur.

**Comment by pfn** [comment]
What is your device configuration?

**Comment by teresaejunior** [comment]
It is a Redmi 2 Pro, with a Qualcomm Snapdragon 410 MSM8916 1,2 GHz CPU, 2 GB RAM, the system is MIUI Global 7.1.3 Stable (based on Android 4.4.4), Linux 3.10.28.

**Comment by pfn** [comment]
If this is your device
http://hanhuy-acra.appspot.com/public/com.hanhuy.android.keepshare.lite/d0f4b64003242264763983f3d199fe2c790f7da9
--
it looks like a crypto error, although unknown why at the moment.

**Comment by teresaejunior** [comment]
Yes, this should be my device! As a side note, on repeated tests, I don't see this problem with my Wifi connection!

**Comment by teresaejunior** [comment]
I have managed to find an application that changes the DNS without root using some VPN foo. I'll be using the Google DNS with the 4G network for the next few days, and will report if I see improvements! I'm insisting on the DNS thing because I seem to have found better results with the VPN, and ISP DNS servers are known to be very shitty!

**Comment by teresaejunior** [comment]
I have tried reproducing this issue for the last weeks without success, but I've spent lask week traveling, and I could pin down the problem to this particular 4G carrier, called TIM Brasil. Other 4G carriers did not present this same problem!

**Comment by pfn** [comment]
Thanks for following up on this. I will have to figure out something for
the future that allows some measure of offline use.

Probably something along the lines of:

Detect whether the device has a hardware key store
Use hardware keystore if available
Delete from keystore on multiple failures to authenticate.
