### ISSUE TITLE
Setting up pin gives error message

### ISSUE THREAD

**Issue by miotum** [pfn/keepshare#32]
I added a database to keepshare lite on Nexus 5x on Andorid 7.0 from google play store.

When I try to setup a pin it will give an error message: 
Failed to save new pin:
[Ljava.lang.String;@f114df2 (of class [Ljava.lang.String;)

Restarting and reinstalling does not help.

Is there any way to solve this problem?

**Comment by pfn** [comment]
There appears to be a bug on nougat, I will need to investigate. However, I
am currently unavailable for the next few weeks

**Comment by pfn** [comment]
This should have been fixed by 74721fbee50db65b7952fc18bfcaaf8c94529a53
