### ISSUE TITLE
High potential security issue 

### ISSUE THREAD

**Issue by Sudheer2011** [pfn/keepshare#33]
Personally I feel overall app performance is really good (smooth & polished), but, I see there is a potential security issue with the clipboard.  

Yes, I know Keepshare app has auto fill option, but honestly most of the times its not working, so the only option is to copy both username & password and then use it for logins. 

However, when you copy credentials, they will be stored in a clipboard which is I believe is very dangerous. 
I have checked even after 5 min, still I can paste my password (this is something very dangerous). 

How to deal with this:

Maybe App has to implement some sort of setting to clear out clipboard after few seconds, I see Keepass is also uses same approach. 

I'm not a techie to help you with the code, but in case if you need any other help with testing etc, I'm happy to help.

Overall I'd say good work.!!

Thanks

**Comment by pfn** [comment]
Yes, not clearing the clipboard is an oversight, however, it is not an
endorsed method of using credentials; use the keyboard.

What apps are you having a problem with auto-fill? It rarely fails and
works well across all apps I have tested. The only instance when it fails,
typically is when the service dies (usually a poorly tuned ROM).

**Comment by Sudheer2011** [comment]
Thanks for your reply!

well, I have again installed Digilocker app and tried to use auto-fill functionality, but didn't work. Instead, I have started using Keyboard. It works well. 

Maybe a suggestion, why don't you create a tutorial on how to use KeepShare, Honestly till today I don't know how to use Keyboard option. 

Anyway, I'd really appreciate your hard work.
