### ISSUE TITLE
Can't open Keepass database after installing KeepShare Lite app

### ISSUE THREAD

**Issue by louagej** [pfn/keepshare#43]
Hi,

I was able to install and connect to my Database.kdb on Google Drive.
But after that, I can't open my database anymore in the Keepass Windows app.
Is it possible, KeepShare changes the database password or automatically adds a key to open the database?

Kind regards,
Job

**Comment by pfn** [comment]
No, keepshare does not modify the database when opening.

**Comment by louagej** [comment]
Hi Perry,
Thank you for your quick response.
Any suggestions where I can start searching for a solution?
I can still open the db with the KeepShare app but Windows Keepass can't open the db anymore.
Kind regards,
Job

**Comment by pfn** [comment]
Revert the version in Google drive

**Comment by louagej** [comment]
Hi Perry,
The desktop application is working again.
Thanks you for the workaround.
Job
