### ISSUE TITLE
KeepShare crashes on entry view screen + entry edit

### ISSUE THREAD

**Issue by thy1985** [pfn/keepshare#7]
Hi

I bought KeepShare after I tried KeepShare Lite.

It crashes reprodcubable when doing the following steps:
0. Use kdb (v2) file that works with Windows KeePass and other tools on local storage
1. click on a group
2. click on an entry to view it
3. KeepShare hangs, crashes, restarts (shows Pin entry), thus no viewing of PW or entry editing is possible

While KeepShare is a great tool this is a dealbreaker. Is there a chance that you fix this issue?
I that an issue specific to me (CM12, Android 5.0.2, Oneplus One)?
Can I provide something to support debugging? is there a way for refund if it is a won't fix?

Thanks & Cheers,
Thy

**Comment by pfn** [comment]
I'm confused, is the issue you are encountering while trying to /edit/ or just view?

**Comment by pfn** [comment]
There are no known crashes while simply opening an entry. I have seen reports of crashes while clicking edit (to which I have not yet found the problem yet)

**Comment by thy1985** [comment]
Once i click an entry it is display but the app freezes immediately. (can't click anything).

**Comment by thy1985** [comment]
If there is anything I can help to debug I'll give it a try
Logical maybe?

**Comment by pfn** [comment]
If it freezes, and only produces an ANR without crashing, then
/data/traces/anr.txt would be useful. adb pull /data/traces/anr.txt when
the "WAIT/CLOSE" dialog pops up. Otherwise, nothing has shown up in crash
logs, maybe pull a logcat in case it's not getting submitted.

**Comment by thy1985** [comment]
Looks like there is no /data/traces dir, I also verified that with UID 0/root:
```
thilo@rmbp [~]$ sudo adb pull  /data/traces/anr.txt
remote object '/data/traces/anr.txt' does not exist
thilo@rmbp [~]$ sudo adb shell
COLUMNS=238;LINES=56;export COLUMNS LINES;
shell@A0001:/ $ cd /data/traces
/system/bin/sh: cd: /data/traces: No such file or directory
2|shell@A0001:/ $ cd /data
shell@A0001:/data $ ls
opendir failed, Permission denied
255|shell@A0001:/data $ su
COLUMNS=238;LINES=56;export COLUMNS LINES;
root@A0001:/data # whoami
whoami: unknown uid 0
1|root@A0001:/data # ls
anr
app
app-asec
app-lib
app-private
audio
backup
bugreports
cam_socket1
cam_socket2
camera
connectivity
dalvik-cache
data
dontpanic
dpm
drm
fdAlbum
local
lost+found
media
mediadrm
misc
nfc
opponvitems
property
resource-cache
security
shared
system
time
user
root@A0001:/data # cd traces
tmp-mksh: cd: /data/traces: No such file or directory
2|root@A0001:
```

Looks like my firewall was unintentionally blocking crash reports. After I corrected that I can see in logcat instead of a Java stack trace about connection refused the following message:
```06-22 20:50:25.366 D/ACRA    (30964): Sending request to http://hanhuy-acra.appspot.com/api/crashreport
```

I assume that means you should have received a crash report now?

**Comment by pfn** [comment]
/data/anr/traces.txt

**Comment by thy1985** [comment]
From my systems build.props I figured that the locations is: /data/anr/traces.txt.

See:
http://pastebin.com/yKnqe8wv

**Comment by pfn** [comment]
Yeah, that traces.txt is too late, need it copied while the "WAIT" dialog
is showing"

**Comment by pfn** [comment]
Can you submit the error when it prompts you? That should give me something I can work with in the developer console.

**Comment by thy1985** [comment]
I tried hard to pull the trace while the wait dialog is there or even submit a report. Not so easy as most of the hanging (up to 7 seconds) is with no dialog (and no trace file). Then sometimes if I click like crazy on the hanging UI the wait + submit report dialog shows for a second or shorter (I see it flashing past) and is replaced by the pin entry screen of keepshare. Sometimes I can't even see the dialog at all. If I succeed I'll let you know / submit a report.

**Comment by pfn** [comment]
You should be able to get a usable traces.txt if you wait 10 seconds after the app fails to respond. Maybe 9 seconds would be ok. Default android behavior is to pop up the not responding dialog after 10 seconds. The traces.txt should be updated correctly by that time.

**Comment by thy1985** [comment]
Problem here is that after 7 seconds of hang KeepShare returns to the unlock UI. So there is no such dialog. I tried pulling multiple traces in a while loop during the hang but that produced no trace files differing from the one I pasted already. Can I maybe download the source and debug with Android Studio?

**Comment by pfn** [comment]
You can import it into intellij and debug.

Intellij => install scala plugin
import project => debug

but you need to have a debug build first...

**Comment by thy1985** [comment]
Finally I found a little time to follow up on this. Installed intellij + scala plugin + scala idk (java/android sdks existing already) and imported your project (4.1.5 release)

Android API 21 & Scala SDK are configured as external Libraries.
Looks like the support lib project (appcompat) is somehow missing:
```
Error:(3, -1) android-apt-compiler: [main] [...]/keepshare-4.1.5/src/main/res/values/styles.xml:3: error: Error retrieving parent for item: No resource found that matches the given name 'Theme.AppCompat.Light'.
```

Do you have a hint what I need to do in order to resolve that? I have this in my Android SDK:
/Library/Android/sdk/extras/android/support/v7/appcompat

How do I reference it in the project? In the module settings the main/libs/andoird-v4-support-compat.jar that came with your release is referenced.

**Comment by pfn** [comment]
The build must be performed with sbt

--

**Comment by pfn** [comment]
http://www.hanhuy.com/~pfnguyen/keepshare-debug.apk

In the interest of making it easier for you to debug, please use the above build, it is 4.1.6.

Just run it and attach the debugger from intellij.

**Comment by thy1985** [comment]
thanks a lot - will use this once I find the time. there is one more logcat for now.

Does it help?


```
(14282): ACRA caught a StackOverflowError for com.hanhuy.android.keepshare
E/ACRA    (14282): java.lang.StackOverflowError: stack size 8MB
E/ACRA    (14282): 	at android.view.View.invalidateInternal(View.java:11664)
E/ACRA    (14282): 	at android.view.View.invalidate(View.java:11626)
E/ACRA    (14282): 	at android.widget.TextView.invalidateRegion(TextView.java:4885)
E/ACRA    (14282): 	at android.widget.TextView.invalidateCursor(TextView.java:4828)
E/ACRA    (14282): 	at android.widget.TextView.spanChange(TextView.java:7758)
E/ACRA    (14282): 	at android.widget.TextView$ChangeWatcher.onSpanAdded(TextView.java:9467)
E/ACRA    (14282): 	at android.text.SpannableStringInternal.sendSpanAdded(SpannableStringInternal.java:314)
E/ACRA    (14282): 	at android.text.SpannableStringInternal.setSpan(SpannableStringInternal.java:138)
E/ACRA    (14282): 	at android.text.SpannableString.setSpan(SpannableString.java:46)
E/ACRA    (14282): 	at android.text.SpannableStringInternal.<init>(SpannableStringInternal.java:52)
E/ACRA    (14282): 	at android.text.SpannableString.<init>(SpannableString.java:30)
E/ACRA    (14282): 	at android.widget.TextView.removeSuggestionSpans(TextView.java:4194)
E/ACRA    (14282): 	at android.widget.TextView.setText(TextView.java:3920)
E/ACRA    (14282): 	at android.widget.TextView.setText(TextView.java:3905)
E/ACRA    (14282): 	at android.widget.TextView.getIterableTextForAccessibility(TextView.java:9036)
E/ACRA    (14282): 	at android.view.View.onInitializeAccessibilityEventInternal(View.java:5445)
E/ACRA    (14282): 	at android.view.View.onInitializeAccessibilityEvent(View.java:5417)
E/ACRA    (14282): 	at android.widget.TextView.onInitializeAccessibilityEvent(TextView.java:8391)
E/ACRA    (14282): 	at android.view.View.sendAccessibilityEventUncheckedInternal(View.java:5288)
E/ACRA    (14282): 	at android.view.View.sendAccessibilityEventUnchecked(View.java:5275)
E/ACRA    (14282): 	at android.view.View.sendAccessibilityEventInternal(View.java:5252)
E/ACRA    (14282): 	at android.view.View.sendAccessibilityEvent(View.java:5221)
E/ACRA    (14282): 	at android.widget.TextView.sendAccessibilityEvent(TextView.java:8560)
E/ACRA    (14282): 	at android.widget.TextView.onSelectionChanged(TextView.java:7573)
E/ACRA    (14282): 	at android.widget.TextView.spanChange(TextView.java:7773)
E/ACRA    (14282): 	at android.widget.TextView$ChangeWatcher.onSpanAdded(TextView.java:9467)
E/ACRA    (14282): 	at android.text.SpannableStringInternal.sendSpanAdded(SpannableStringInternal.java:314)
E/ACRA    (14282): 	at android.text.SpannableStringInternal.setSpan(SpannableStringInternal.java:138)
E/ACRA    (14282): 	at android.text.SpannableString.setSpan(SpannableString.java:46)
E/ACRA    (14282): 	at android.text.SpannableStringInternal.<init>(SpannableStringInternal.java:52)
E/ACRA    (14282): 	at android.text.SpannableString.<init>(SpannableString.java:30)
E/ACRA    (14282): 	at android.widget.TextView.removeSuggestionSpans(TextView.java:4194)
E/ACRA    (14282): 	at android.widget.TextView.setText(TextView.java:3920)
E/ACRA    (14282): 	at android.widget.TextView.setText(TextView.java:3905)
E/ACRA    (14282): 	at android.widget.TextView.getIterableTextForAccessibility(TextView.java:9036)
E/ACRA    (14282): 	at android.view.View.onInitializeAccessibilityEventInternal(View.java:5445)
E/ACRA    (14282): 	at android.view.View.onInitializeAccessibilityEvent(View.java:5417)
E/ACRA    (14282): 	at android.widget.TextView.onInitializeAccessibilityEvent(TextView.java:8391)
E/ACRA    (14282): 	at android.view.View.sendAccessibilityEventUncheckedInternal(View.java:5288)
E/ACRA    (14282): 	at android.view.View.sendAccessibilityEventUnchecked(View.java:5275)
E/ACRA    (14282): 	at android.view.View.sendAccessibilityEventInternal(View.java:5252)
E/ACRA    (14282): 	at android.view.View.sendAccessibilityEvent(View.java:5221)
E/ACRA    (14282): 	at android.widget.TextView.sendAccessibilityEvent(TextView.java:8560)
E/ACRA    (14282): 	at android.widget.TextView.onSelectionChanged(TextView.java:7573)
E/ACRA    (14282): 	at android.widget.TextView.spanChange(TextView.java:7773)
E/ACRA    (14282): 	at android.widget.TextView$ChangeWatcher.onSpanAdded(TextView.java:9467)
E/ACRA    (14282): 	at android.text.SpannableStringInternal.sendSpanAdded(SpannableStringInternal.java:314)
E/ACRA    (14282): 	at android.text.SpannableStringInternal.setSpan(SpannableStringInternal.java:138)
E/ACRA    (14282): 	at android.text.SpannableString.setSpan(SpannableString.java:46)
E/ACRA    (14282): 	at android.text.SpannableStringInternal.<init>(SpannableStringInternal.java:52)
E/ACRA    (14282): 	at android.text.SpannableString.<init>(SpannableString.java:30)
E/ACRA    (14282): 	at android.widget.TextView.removeSuggestionSpans(TextView.java:4194)
E/ACRA    (14282): 	at android.widget.TextView.setText(TextView.java:3920)
E/ACRA    (14282): 	at android.widget.TextView.setText(TextView.java:3905)
E/ACRA    (14282): 	at android.widget.TextView.getIterableTextForAccessibility(TextView.java:9036)
E/ACRA    (14282): 	at android.view.View.onInitializeAccessibilityEventInternal(View.java:5445)
E/ACRA    (14282): 	at android.view.View.on
D/ACRA    (14282): Building report
D/ACRA    (14282): Using default Report Fields
essibilityEventInternal(View.java:5445)
E/ACRA    (14282): 	at android.view.View.on
D/ACRA    (14282): Building report
D/ACRA    (14282): Using default Report Fields
80ms
```

**Comment by pfn** [comment]
If this is consistently the crash you're seeing, I have no idea how to fix it as I cannot reproduce it locally and the entirety of the stack is in android framework code :-(

**Comment by pfn** [comment]
give 4.1.8 a try?

**Comment by thy1985** [comment]
Yes, when I saw the Stacktrace I already suspected that it won't help as it is just within android classes. I tired 4.1.8. same behavior.

I gave up for now. I use KeepShare for form filling and another tool to View/Edit the DB.

Thanks anyway for your help!

**Comment by pfn** [comment]
Do you mean you're getting the same stack?

Or does that hang occur without a stack

--

**Comment by pfn** [comment]
If you're not seeing that stack anymore, I'd appreciate if you could step through it with the debugger sometime (with the old version I pointed out to you) to see where it hangs so that I can address the issue.

**Comment by thy1985** [comment]
"same behaviour" means same freeze/return to pin entry screen. didn't check the log. I will get back to you, just give me a few more days. :)

**Comment by thy1985** [comment]
i feel somewhat stupid, but when I attach the debugger to the running KeepShare Process on my smartphone I simply see:

```
Connected to the target VM, address: 'localhost:8600', transport: 'socket'
```
And once it crashes:
```
Disconnected from the target VM, address: 'localhost:8600', transport: 'socket'
```

**Comment by pfn** [comment]
I would set a breakpoint at EntryEditFragment.onCreateView to make sure it runs through its entirety.

**Comment by whiskeyzulu** [comment]
I'm also seeing this behavior on my LG G3, Android 5.0.1.

Viewing any entry will cause Keepshare to hang for a few seconds and then crash back to the home screen.

**Comment by thy1985** [comment]
I reflashed my device in the meanwhile a couple of times and upgraded to 5.1.1. No such issue for me anymore. Also stock reflashed to 5.0.2 with everything restored from backup it was working. Functional wise system was in same state. No idea what differs...

**Comment by pfn** [comment]
This is interesting in the behavior change. Did you have a PIN set and now
have it unset or vice versa?

**Comment by digitalkram** [comment]
No. With and without the issue I had a PIN set. 

-------- Ursprüngliche Nachricht --------
Von: 
Gesendet: 10. September 2015 21:35:53 MESZ
An: pfn/keepshare
CC: 
Betreff: Re: [keepshare] KeepShare crashes on entry view screen + entry edit (#7)

This is interesting in the behavior change. Did you have a PIN set and now
have it unset or vice versa?

On Thu, Sep 10, 2015 at 6:14 AM, thy1985 notifications@github.com wrote:

> I reflashed my device in the meanwhile a couple of times and upgraded to
> 5.1.1. No such issue for me anymore. Also stock reflashed to 5.0.2 with
> everything restored from backup it was working. Functional wise system was
> in same state. No idea what differs...
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/pfn/keepshare/issues/7#issuecomment-139230860.

---

**Comment by whiskeyzulu** [comment]
Same here, I've had the issue with and without a PIN, before and after
reinstalling and before and after upgrading from Android 5.0.0 to 5.0.1.
The only differing detail I can recall is that I do know that the issue did
not exist at some point before upgrading to Lollipop, else I wouldn't have
paid for the app, but I can't say for certain that that detail is pertinent.

**Comment by whiskeyzulu** [comment]
I may have been mistaken about the issue existing without a PIN. Tonight I
tried once more and everything worked as expected, until I set the PIN, at
which point things broke.

**Comment by pfn** [comment]
please re-validate on 4.2.0; many changes occurred around the edit fields that may have resolved the issue.

**Comment by pfn** [comment]
closing due to lack of feedback (and lack of crash reports)

**Comment by thy1985** [comment]
Pfn 

Sorry! Had a hard time at work and two weeks back my son was born.... 

Anyway, it seems this issue was specifically related to my system / rom. 

Since an ota or a reflash of the current rom (not sure what came first) this is no longer happening to me. I am a happy keepshare user now! 


Sorry again for my lack of feedback. Somehow lost track of it. And thanks for your responsiveness in this matter! :-)

**Comment by pfn** [comment]
Congratulations on the birth of your son; he will be a wonderful bundle of joy.

Thanks for following up and letting me know this is no longer a problem for you.
